### PR TITLE
Create gentx-e8058f9df7a6ec7736994cea8fba4a3974b136fb.json

### PR DESCRIPTION
**Pull request by MJBaek**
lunemint 's gentx

### CODE REVIEW

**Comment by kidinamoto01** [comment]
Valid gentx, nice job!

**Comment by kidinamoto01** [comment]
Not valid

**Comment by kidinamoto01** [comment]
Not valid

**Comment by MJBaek** [comment]
After updating to Iris 0.9.0
I wrote the command iris gentx --name = lunemint and am I wrong?

**Pull request closed without merging**
