### PR TITLE
Create Wetez.json

### PR DESCRIPTION
**Pull request by wetezos**

### CODE REVIEW

**Comment by kidinamoto01** [comment]
Not valid

**Comment by HaoyangLiu** [comment]
Your software is wrong. Maybe you used `cosmos gaiad` to generate the genTx. You can download the correct software from https://github.com/irisnet/irishub/releases/tag/v0.10.0

**Comment by wetezos** [comment]
> Your software is wrong. Maybe you used `cosmos gaiad` to generate the genTx. You can download the correct software from https://github.com/irisnet/irishub/releases/tag/v0.10.0

我已经修改好了，还可以合并吗，可以的话，辛苦帮忙和一下，谢谢🙏

**Comment by kidinamoto01** [comment]
Gentx submission deadline is already passed

**Pull request closed without merging**
